# Generated by Django 6.0.6 on 2026-06-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebula', '0003_adminuser_customeruser_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
