# Generated by Django 6.0.6 on 2026-06-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebula', '0004_delete_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
